serudda/side-ui

- package.json
> chore: change author name

- package.json
- src/components/Inputs/Textarea/Textarea.tsx
> refactor: improve Textarea styles

- src/components/Buttons/Button/Button.tsx
- Extend Button component in order to add a new prop named "loadingText"
> refactor: include a new prop named "loadingText" into Button

- package.json
- pnpm-lock.yaml
- src/common/types/index.ts
- src/common/types/key.ts
- src/components/Buttons/Button/Button.tsx
- src/components/Overlays/Modals/BaseModal/BaseModal.stories.tsx
- src/components/Overlays/Modals/BaseModal/BaseModal.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.stories.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.tsx
- src/components/Overlays/Modals/ModalContainer.tsx
- src/components/Overlays/Modals/index.ts
- src/components/Overlays/index.ts
- src/hooks/index.ts
- src/hooks/useBodyClass/useBodyClass.ts
- src/hooks/useKeyPress/useKeyPress.ts
- src/hooks/useModal/useModal.tsx
- src/index.css
- tailwind.config.js
- A new component category called "Overlay/Modals" has been added.
- Two new components were included in this new category: BaseModal and ConfirmationModal.
https://github.com/serudda/side-ui/assets/10075532/8b5a5cc1-2ee6-4f74-8da1-62947bea03a4
https://github.com/serudda/twon/issues/41
> [SU-41] include a confirmation modal

- package.json
- pnpm-lock.yaml
- src/common/types/index.ts
- src/common/types/key.ts
- src/components/Buttons/Button/Button.tsx
- src/components/Overlays/Modals/BaseModal/BaseModal.stories.tsx
- src/components/Overlays/Modals/BaseModal/BaseModal.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.stories.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.tsx
- src/components/Overlays/Modals/ModalContainer.tsx
- src/components/Overlays/Modals/index.ts
- src/components/Overlays/index.ts
- src/hooks/index.ts
- src/hooks/useBodyClass/useBodyClass.ts
- src/hooks/useKeyPress/useKeyPress.ts
- src/hooks/useModal/useModal.tsx
- src/index.css
- tailwind.config.js
0.4.0 (Jun 11, 2023)
Added
- A new category called "Overlay/Modals".
- Added two new components within this category: BaseModal and ConfirmationModal.
- Added 3 new hooks: useBodyClass, useModal, andseKeyPress.
> Release 0.4.0

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-failing-test.yml
- .github/ISSUE_TEMPLATE/3-docs-bug.yml
- .github/ISSUE_TEMPLATE/4-feature-request.yml
- .github/ISSUE_TEMPLATE/5-enhancement-request.yml
- .github/ISSUE_TEMPLATE/6-security-report.yml
- .github/ISSUE_TEMPLATE/7-question-support.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/labels.yml
- .github/workflows/labels.yml
- - [X] feat(workflow): ✨ add labels actions to update labels
Update the labels with the GitHub actions labels
add the issues template to be more organize with the issue creation
- #10
> [SU-10] actions and issues

- package.json
- pnpm-lock.yaml
- src/common/constants/breakpoints.ts
- src/common/constants/index.ts
- src/common/utils/helpers.ts
- src/hooks/index.ts
- src/hooks/useBreakpoint/useBreakpoint.ts
- src/hooks/useWindowSize/useWindowSize.ts
Include 2 new hooks: **useWindowSize** and **useBreakpoint**
> Include usebreakpoint

- README.md
- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/ES/CODE_OF_CONDUCT_ES.md
- docs/ES/CONTRIBUTING_ES.md
- docs/ES/SECURITY_ES.md
- docs/ES/SUPPORT_ES.md
- docs/SECURITY.md
- docs/SUPPORT.md
Updated README for better understanding of how to use this project.
Added CONTRIBUTING, CODE OF CONDUCT, SECURITY, and SUPPORT documentation, including a Spanish version.
- #42
> [SU-42] update documentation of this project

- package.json
- src/common/utils/cn.ts
- src/common/utils/index.ts
In this pull request, I have made the following changes:
1. Added `tailwind-merge` and `clsx` dependencies to the `package.json` file to enhance class handling and merging capabilities.
2. Introduced a new utility module `cn.tsx` to provide a streamlined method for combining and merging Tailwind CSS classes. This utility leverages the `twMerge` function from `tailwind-merge` and the `clsx` utility to ensure effective class merging, preventing conflicts and collisions between classes.
-  #47 
EXAMPLE:
```tsx
export const Div = ({className}: {className: string}) => {
const classes = {
container: cn('bg-red-400 px-4 py-6', className),
}
return (
<div className={classes.container}> 
<h1> Zyruks </h1>
</div>
)
}
```
USE:
```tsx
<Div className='bg-blue-500 p-10' /> 
```
OUTPUT WITHOUT UTILITY: …
> [SU-47] tailwind collision

- src/components/Buttons/Button/Button.tsx
- [extend Button variants](https://github.com/serudda/side-ui/commit/13e12f2f4e61711dfc8706135be6b7c55e37f7e2)
> refactor: extend Button variants

- src/common/utils/index.ts
- src/common/utils/mergeProps.ts
- src/components/Buttons/Button/Button.stories.tsx
- src/components/Buttons/Button/Button.tsx
- src/components/Buttons/CopyButton/CopyButton.stories.tsx
- src/components/Icon/Icon.tsx
- src/components/Loaders/Spinner/Spinner.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/BasicModalHeader/BasicModalHeader.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/FullScreenModalHeader/FullScreenModalHeader.tsx
- src/components/Slot/Slot.tsx
- src/components/index.ts
- src/hooks/index.ts
- src/hooks/useMultipleRefs/useMultipleRefs.tsx
- tailwind.config.js
In order to be able to have more control in the form and use of the Button component... we created a new component called "Slot" which allows us to inherit the shape of the children.
THIS IS A BREAKING CHANGE... IT IS NECESSARY TO REPLACE ALL THE BUTTONS SO THAT THEY CAN USE THE NEW STRUCTURE.
> Define a new component named "Slot"

- .husky/commit-msg
- .husky/pre-commit
- .huskyrc
- .lintstagedrc
- commitlint.config.cjs
- package.json
- Added the prepare script to the `package.json` file.
- Added the `lintstagerc` file to lint with prettier and eslint.
- added the `commitlint.config.cjs` file with new rules.
- #56
> [SU-56] ✨ add husky, commitlint, linstage with config

- src/components/Avatar/Avatar.tsx
- src/components/Buttons/Button/Button.tsx
- src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
- src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
- src/components/Controls/Stepper/Stepper.tsx
- src/components/Controls/Switch/Switch.tsx
- src/components/DropdownMenu/Menu/Menu.tsx
- src/components/DropdownMenu/Option/Option.tsx
- src/components/Icon/Icon.tsx
- src/components/Image/Image.tsx
- src/components/Inputs/Select/Select.tsx
- src/components/Inputs/TextInput/TextInput.tsx
- src/components/Inputs/Textarea/Textarea.tsx
- src/components/NewsTag/NewsTag.tsx
- src/components/Notifications/Toast/Toast.tsx
- src/components/Notifications/Toast/ToastContainer.tsx
- src/components/Overlays/Modals/BaseModal/BaseModal.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.tsx
- src/components/Overlays/Modals/ModalContainer/ModalContainer.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/BasicModalHeader/BasicModalHeader.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/FullScreenModalHeader/FullScreenModalHeader.tsx
- src/components/Overlays/Popover/Popover.tsx
- src/components/Overlays/Tooltip/Tooltip.tsx
- src/components/Progress/ProgressCircle/ProgressCircle.tsx
- src/components/Tag/Tag.tsx
Update most of the component to use the new `cn` utility function
- #65
> chore: update cn utility

- src/components/Buttons/CopyButton/CopyButton.tsx
- src/components/Inputs/TextInput/TextInput.tsx
- src/components/Notifications/Toast/Toast.stories.tsx
- src/components/Notifications/Toast/Toast.tsx
- src/components/Notifications/Toast/ToastContainer.tsx
> Connect with typefully

- src/components/Avatars/Avatar/Avatar.tsx
- src/components/Avatars/StackedAvatar/StackedAvatar.stories.tsx
- src/components/Avatars/StackedAvatar/StackedAvatar.tsx
- src/components/Overlays/Tooltip/Tooltip.stories.tsx
- src/components/Overlays/Tooltip/Tooltip.tsx
- src/components/Overlays/Tooltip/Trigger/Trigger.tsx
- [Extend Tooltip component to add a show and hide delay time](https://github.com/serudda/side-ui/commit/55b9cabd9e835786ee92067940d84e48f386ea95)
- [Extend Tooltip component with a Tooltip.Trigger component](https://github.com/serudda/side-ui/commit/eb994aaf021c6b6677e67355da7d3524810fe185)
> Release v0.16.3

- src/components/Inputs/TextInput/TextInput.tsx
UI Guidelines necessitates the modification of this component to ensure its compatibility with both dark and light modes.
These alterations will incorporate a transition effect and a new hover state, enhancing its visual appeal and interactivity.
https://github.com/serudda/side-ui/assets/14036522/e2988f8e-fc07-44e3-b4ca-bc444f3d5733
https://github.com/serudda/side-ui/assets/14036522/582abde6-953d-4624-b6bf-4983b7f5b8a8
> Feature update text input

- src/components/Inputs/TextInput/TextInput.tsx
- Extends Text Input component to add a light and dark color
> Release 0.16.5

- src/components/Overlays/Modals/BaseModal/BaseModal.tsx
- src/components/Overlays/Modals/ConfirmationModal/ConfirmationModal.stories.tsx
- src/components/Overlays/Modals/ModalSections/ModalBody/ModalBody.tsx
- src/components/Overlays/Modals/ModalSections/ModalContent.tsx
- src/components/Overlays/Modals/ModalSections/ModalFooter/ModalFooter.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/ModalHeader/ModalHeader.tsx
- Update broken class 
- Update `cn` function
- Update dark/light mode
- Add modal sizes
- Issue Number
> Refactor / update modal

- src/components/Overlays/Modals/ModalSections/ModalBody/ModalBody.tsx
- src/components/Overlays/Modals/ModalSections/ModalFooter/ModalFooter.tsx
- src/components/Overlays/Modals/ModalSections/ModalHeaders/ModalHeader/ModalHeader.tsx
> General improvement o the Modal component

- src/components/Icon/Icon.tsx
- src/components/Inputs/TextInput/TextInput.tsx
Introduced a new 'magnifyingGlass' icon to the IconCatalog enumeration and implemented its design within the Icons record. Adjusted icon-related class handling by removing an extra space in the conditional expression for better consistency. Extended TextInput component with an 'inputContainerClassName' prop to allow custom styling on the InputContainer, enhancing UI versatility.
> refactor(components): ♻️ add magnifying glass icon; refine  input styles

- src/components/Inputs/TextInput/TextInput.tsx
Revise the colors used for the focus state to enhance adaptability and customization. This revision ensures the focus state is not strictly tied to a specific color, allowing it to seamlessly integrate with various project color schemes.
> refactor(text-input): ♻️ update focus color for text input

- src/components/Breadcrumbs/Breadcrumbs.tsx
> HOTFIX: update Breadcrumbs container style

- src/components/Image/Image.tsx
In this PR, we address a crucial fix within our `Image` component to enhance its dynamic behavior in response to prop updates. Specifically, we have introduced a new `useEffect` hook that monitors changes to the `src` prop. Upon detection of a change, this hook resets the `imageSrc`, `hasAttemptedFallback`, and `imageLoaded` states. This adjustment ensures that our component can dynamically update the displayed image and correctly handle the fallback image logic, should the new source fail to load. This enhancement is pivotal for ensuring our `Image` component remains robust and responsive in environments where image URLs may change based on user interaction or other asynchronous events.
> fix(components): 🐛 Ensure Image component updates on src prop change

- src/components/Overlays/Modals/BaseModal/BaseModal.stories.tsx
- src/components/Overlays/Modals/ModalRoot.tsx
- src/components/Overlays/Modals/ModalSections/ModalContent.tsx
- [FullScreen improvement on the Modal component](https://github.com/serudda/side-ui/commit/3976b7436c42cbad05980de225de7839e115c590)
> Improve Full Screen version of the Modal component
